### ISSUE TITLE
python3.8 ———— ModuleNotFoundError: No module named 'DataGrabber'

### ISSUE THREAD

**Issue by bf109f4** [QY7/DataGrabber#1]
运行main.py时报错
Traceback (most recent call last):
  File "e:/ProkrameDemo/曲线数值提取软件/DataGrabber-main/main.py", line 2, in <module>
    from src.DataGrabber.launcher import datagrabber
  File "e:\ProkrameDemo\曲线数值提取软件\DataGrabber-main\src\DataGrabber\launcher.py", line 7, in <module>    
    from .datagrabber import mywindow
  File "e:\ProkrameDemo\曲线数值提取软件\DataGrabber-main\src\DataGrabber\datagrabber.py", line 19, in <module>
    from DataGrabber import _root_path
ModuleNotFoundError: No module named 'DataGrabber'

datagrabber.py这个文件中导入是
import os
from .find_contour import find_box
import json
from DataGrabber import _root_path
from DataGrabber.local_log import log_print

**Comment by bf109f4** [comment]
问题已解决，把from DataGrabber import _root_path里的DataGrabber  改成. 就行

**Comment by QY7** [comment]
感谢
